//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAlumno {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppAlumno.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string btnAbrir {
            get {
                return ResourceManager.GetString("btnAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Agenda.
        /// </summary>
        internal static string btnAgenda {
            get {
                return ResourceManager.GetString("btnAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ●  Configuracion.
        /// </summary>
        internal static string btnConfiguracion {
            get {
                return ResourceManager.GetString("btnConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        internal static string btnCrear {
            get {
                return ResourceManager.GetString("btnCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Docentes.
        /// </summary>
        internal static string btnDocentes {
            get {
                return ResourceManager.GetString("btnDocentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar cuenta.
        /// </summary>
        internal static string btnEliminarCuenta {
            get {
                return ResourceManager.GetString("btnEliminarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string btnEnviar {
            get {
                return ResourceManager.GetString("btnEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar.
        /// </summary>
        internal static string btnExaminar {
            get {
                return ResourceManager.GetString("btnExaminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atras.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar.
        /// </summary>
        internal static string btnFinalizar {
            get {
                return ResourceManager.GetString("btnFinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ●  Institucion.
        /// </summary>
        internal static string btnInstitucion {
            get {
                return ResourceManager.GetString("btnInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Cerrar sesion.
        /// </summary>
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Mensajes.
        /// </summary>
        internal static string btnMensajes {
            get {
                return ResourceManager.GetString("btnMensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Mi perfil.
        /// </summary>
        internal static string btnMiPerfil {
            get {
                return ResourceManager.GetString("btnMiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ●  Mis asignaturas.
        /// </summary>
        internal static string btnMisAsignaturas {
            get {
                return ResourceManager.GetString("btnMisAsignaturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ●  Mis docentes.
        /// </summary>
        internal static string btnMisDocentes {
            get {
                return ResourceManager.GetString("btnMisDocentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ●  Mis mensajes.
        /// </summary>
        internal static string btnMisMensajes {
            get {
                return ResourceManager.GetString("btnMisMensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ●  Nuevo mensaje.
        /// </summary>
        internal static string btnNuevoMensaje {
            get {
                return ResourceManager.GetString("btnNuevoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Salas.
        /// </summary>
        internal static string btnSala {
            get {
                return ResourceManager.GetString("btnSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse.
        /// </summary>
        internal static string btnUnirse {
            get {
                return ResourceManager.GetString("btnUnirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido:.
        /// </summary>
        internal static string lblApellido {
            get {
                return ResourceManager.GetString("lblApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        internal static string lblAsunto {
            get {
                return ResourceManager.GetString("lblAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar:.
        /// </summary>
        internal static string lblBuscar {
            get {
                return ResourceManager.GetString("lblBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        internal static string lblCambiarPass {
            get {
                return ResourceManager.GetString("lblCambiarPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. 1000 caracteres.
        /// </summary>
        internal static string lblCaracteres {
            get {
                return ResourceManager.GetString("lblCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear sala:.
        /// </summary>
        internal static string lblCrear {
            get {
                return ResourceManager.GetString("lblCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string lblErrorMessage {
            get {
                return ResourceManager.GetString("lblErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto:.
        /// </summary>
        internal static string lblFoto {
            get {
                return ResourceManager.GetString("lblFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click aqui.
        /// </summary>
        internal static string lblLink {
            get {
                return ResourceManager.GetString("lblLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Obligatorio.
        /// </summary>
        internal static string lblObligatorio {
            get {
                return ResourceManager.GetString("lblObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña:.
        /// </summary>
        internal static string lblPassNueva {
            get {
                return ResourceManager.GetString("lblPassNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña anterior:.
        /// </summary>
        internal static string lblPassVieja {
            get {
                return ResourceManager.GetString("lblPassVieja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si aun no te has registrado como usuario/a.
        /// </summary>
        internal static string lblRegistro {
            get {
                return ResourceManager.GetString("lblRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salas:.
        /// </summary>
        internal static string lblSalas {
            get {
                return ResourceManager.GetString("lblSalas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario:**.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string txtContra {
            get {
                return ResourceManager.GetString("txtContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string txtUsuario {
            get {
                return ResourceManager.GetString("txtUsuario", resourceCulture);
            }
        }
    }
}
